name: Build and Release .muxapp

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare .muxapp package
      run: |
        mkdir -p build
        mkdir -p build/PyLauncher
        # Copy everything except .git, README.md, .github and build itself into build/PyLauncher
        rsync -av --exclude='.git' --exclude='README.md' --exclude='.github' --exclude='build' ./ build/PyLauncher/
        # Zip the PyLauncher folder itself, not solo su contenido
        cd build
        zip -r PyLauncher.zip PyLauncher
        mv PyLauncher.zip PyLauncher.muxapp

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/PyLauncher.muxapp
        token: ${{ secrets.GH_PAT }}