name: Build and Release .muxapp

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare .muxapp package
      run: |
        mkdir -p build
        zip -r build/PyLauncher.zip . -x "*.git*" "README.md" ".github/*"
        mv build/PyLauncher.zip build/PyLauncher.muxapp

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/PyLauncher.muxapp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
