name: Attach .muxapp to Release

on:
  release:
    types: [created]

permissions:
  contents: write  # Necesario para subir archivos a un release

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .muxapp archive
        run: |
          mkdir -p build
          zip -r build/PyLauncher.zip . -x "*.git*" "*README*" "*.github*"
          mv build/PyLauncher.zip build/PyLauncher.muxapp

      - name: Upload .muxapp to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/PyLauncher.muxapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
