name: Build and Release .muxzip

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare .muxzip package structure
      run: |
        mkdir -p package/mnt/mmc/MUOS/application/PyLauncher
        mkdir -p package/opt/muos/default/MUOS/theme/active/glyph/muxapp

        # Copy launcher files
        rsync -av --exclude='.git' --exclude='README.md' --exclude='.github' --exclude='build' ./ package/mnt/mmc/MUOS/application/PyLauncher/

        # Copy icon (assumes it's in project root with name pylauncher.png)
        cp pylauncher.png package/opt/muos/default/MUOS/theme/active/glyph/muxapp/

        # Create the final .muxzip
        cd package
        zip -r ../PyLauncher.muxzip .
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: PyLauncher.muxzip
        token: ${{ secrets.GH_PAT }}
